### ISSUE TITLE
Add command prefix

### ISSUE THREAD

**Issue by Morgy93** [ObliviousHarmony/vscode-php-codesniffer#42]
### Problem Description

If you work with docker containers, you cannot use this extension because PHP is only available within the container and not on the host.

### Proposed Solution

It would be awesome if you could provide some command prefix which is a common way to run things inside the container.
E.g. `ddev exec phpcs...` or `bin/run-inside-container phpcs...`

### Additional Context

Let me borrow a live example from https://github.com/phpro/grumphp/blob/v1.8.0/doc/parameters.md

![image](https://user-images.githubusercontent.com/7961978/156654422-0851b981-73b2-43ed-95bd-5de77af695e7.png)

**Comment by ObliviousHarmony** [comment]
Hey @Morgy93,

There's already an `executable` configuration option that should work for this purpose. This isn't the name of an executable but rather the actual executable that is ran.

One concern I have though is that it also passes a path to some classes that are required for PHPCS to return the data we are asking for. I'm not sure that the Docker container would have access to these, and if it does, it's not likely that they are at the same path as the host.

Let me know if that by itself works, and if not, I'll take a look at the use case for a Docker container and think about how we can serve it.

**Comment by Morgy93** [comment]
> Hey @Morgy93,
> 
> There's already an `executable` configuration option that should work for this purpose. This isn't the name of an executable but rather the actual executable that is ran.
> 
> One concern I have though is that it also passes a path to some classes that are required for PHPCS to return the data we are asking for. I'm not sure that the Docker container would have access to these, and if it does, it's not likely that they are at the same path as the host.
> 
> Let me know if that by itself works, and if not, I'll take a look at the use case for a Docker container and think about how we can serve it.

Thanks for quick reply!

Unfortunately, I am unable to change the setting:

![image](https://user-images.githubusercontent.com/7961978/157010446-24c20cfc-e56a-4ff8-ad34-f3a6a294e909.png)

Any idea what's wrong here? Tried to edit the `settings.json` as usual.

**Comment by ObliviousHarmony** [comment]
I have only ever set configuration options using the Settings UI that VS Code provides, so I can't really help you with this one. In my experience, it has provided support for every kind of configuration I've needed in extensions and automatically takes you to the correct `settings.json` file when it requires something more complicated than the UI has.

**Comment by Morgy93** [comment]
> I have only ever set configuration options using the Settings UI that VS Code provides, so I can't really help you with this one. In my experience, it has provided support for every kind of configuration I've needed in extensions and automatically takes you to the correct `settings.json` file when it requires something more complicated than the UI has.

That's the issue here, if using the settings UI, it always changes back to the default value, so I am unable to change it:

![phpcs](https://user-images.githubusercontent.com/7961978/157218365-fa8b1d9a-514d-488b-95ee-849590f3a11e.gif)

**Comment by ObliviousHarmony** [comment]
I'm unable to reproduce this @Morgy93. The scope for this option is `machine-overridable`, so it shouldn't have any problems being overridden. What tab of the settings UI are you making this change on?

<img width="222" alt="Screen%20Shot%20on%202022-03-08%20at%2010-56-55" src="https://user-images.githubusercontent.com/6451942/157306737-64833fac-a7ac-41b4-aaea-830a77bc6eb9.png">

I'm also curious whether or not VS Code is giving you any kind of error message when it sets it back?

**Comment by Morgy93** [comment]
> I'm unable to reproduce this @Morgy93. The scope for this option is `machine-overridable`, so it shouldn't have any problems being overridden. What tab of the settings UI are you making this change on?
> 
> <img alt="Screen%20Shot%20on%202022-03-08%20at%2010-56-55" width="222" src="https://user-images.githubusercontent.com/6451942/157306737-64833fac-a7ac-41b4-aaea-830a77bc6eb9.png">
> 
> I'm also curious whether or not VS Code is giving you any kind of error message when it sets it back?

I'm using the "User" tab as well:

![image](https://user-images.githubusercontent.com/7961978/157461191-d7110341-663a-46f1-9995-6f379101590a.png)

I don't see any error message, except the one on manual edit in the `settings.json`

**Comment by ObliviousHarmony** [comment]
Thanks, @Morgy93, I'll try this out on my Windows machine over the weekend and try to replicate your issue. I'm not sure why it's not letting you commit the change.

The only thing I can think of is that maybe it needs to be edited in the `Remote [WSL: Ubuntu]` tab since the extension isn't running in the local context. Technically speaking, VS Code uses a server in the WSL VM that it communicates with and runs all of the extensions that require that context. The `User` tab I believe is for global settings, but those don't necessarily make sense since the host OS and the remote OS aren't entirely connected. File paths in one wouldn't work in the other, for instance.

I've always configured the extension at a workspace level, so I think that's why I've never seen this before.

**Comment by ObliviousHarmony** [comment]
Hello @Morgy93,

Sorry for the long wait! I've taken a look today and I don't actually see the `phpCodeSniffer.executable` setting in the `User` tab. If I was to make a guess, it's probably that the setting is not configurable at the user `settings.json` file when using a remote extension. It's possible that it used to give this error while now the setting isn't visible at all in that context.

Generally speaking, these extensions work by running a VS Code server on the destination and communicating with it over various methods. You'll note in the extensions interface, for example, that there are two sets of extensions. Those that are installed locally and those that are installed on the remote. The executable path here, for instance, is to a path on the remote, rather than your local installation. When using a remote extension, you should be interacting with code checked out on that filesystem and configure it accordingly.

**Comment by lumnn** [comment]
I don't think this problem is necessarily solved. It's impossible to make extension work, with docker.

**executable option** - it allows specifying custom command, but when command is like `docker-compose exec php vendor/bin/phpcs` then, executable is `docker-compose` and there are extra arguments in front `exec php vendor/bin/phpcs`

**[--report option](https://github.com/ObliviousHarmony/vscode-php-codesniffer/blob/main/src/phpcs-report/worker.ts#L171)** - Docker container will not have an access to the extensions PHP file for preparing the report. I believe safer would be to use a JSON report from PHPCS and then amending it within extension - https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting#printing-a-json-report

**Path mappings** - docker container and real paths may be different. For example XDebug extension uses pathMappings option to rewrite paths so they match host system paths.

![image](https://user-images.githubusercontent.com/2505114/166898188-52a939ae-96c0-4b61-a11b-358982c53d90.png)

Also an extra one that I encountered during a set-up with my project, but not necessarily related to this issue

**Working Directory** - I can see in the code that there are `workingDirectory` properties, but I think they're controllable in any way - or I couldn't get them working by manually entering them in `settings.json` file. This is certainly useful for projects which doesn't have `composer.json` and `.phpcs.xml.dist` inside root folder. Would be nice if this can be changed

**Comment by ObliviousHarmony** [comment]
> I don't think this problem is necessarily solved. It's impossible to make extension work with docker.

To be fair, the issue is an enhancement request for a feature that already exists. While your comment highlights some problems in this use case, that's not necessarily the point of the original issue! I appreciate you taking such a thorough dive into the problem and highlighting specific issues though.

>  it allows specifying custom command, but when command is like `docker-compose exec php vendor/bin/phpcs` then, executable for `child_process.spawn` method is docker-compose and there are extra arguments in front `exec php vendor/bin/phpcs`.

Hmm, what does this end up doing in practice? Technically speaking, running `docker-compose` as the executable is fine, isn't it? The arguments should be getting passed to `docker-compose` and it should work, right? As an aside, I think you also need to pass `-T` to avoid creating a pseudo-TTY. Something like `docker-compose exec -T PHP vendor/bin/phpcs` might work.

> `php7 vendor/bin/phpcs` doesn't work as well for me

Out of curiosity, is the `autoExecutable` configuration option enabled in this case? Even when you set an executable manually it will still try to find one to execute if you've enabled this setting. Can you check the error log and see what it's saying has gone wrong?

Unrelated to the Docker problem, could you open an issue with this information? This problem is specifically that you can't use a custom version of PHP, more or less, so I'd like to dive into that one for certain.

> Docker container will not have an access to the extensions PHP file for preparing the report. I believe safer would be to [use a JSON report from PHPCS](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting#printing-a-json-report) and then amending it within extension. Although I didn't learn through what custom reporting does so I'm not sure whether that's possible at all.

Unfortunately, the custom reporting is responsible for all of the functionality within this extension. The default JSON report only gives you a list of errors and warnings. The custom reports in the extension pull all of the information necessary to implement the "Fix {error}" feature and region formatting options.

One possibility would be for the extension to have an option to copy these report files to a configurable location. This would probably work?

> Path mappings - docker container and real paths may be different. For example XDebug extension uses pathMappings option to rewrite paths so they match host system paths.

Interesting, I think this is a problem because `document.uri.fsPath` is absolute? The path to the file is misrepresented. I could also see this being a problem with the reports, since they use an absolute path too. Some kind of configuration option for mapping paths could solve this problem too.

> Working Directory

This really only serves the purpose of setting the `cwd` of the executable. PHPCS uses this in some very limited circumstances and it's entirely file-dependent. It defaults to the root folder of your workspace, so even if there's no `composer.json` it should be reasonably set.

--

While I see how the extension could be improved by a `fileMapping` feature and a report copying feature, I'm curious about something. Why not use the [remote container extension](https://code.visualstudio.com/docs/remote/containers)? Realistically speaking, it feels like you're jumping through a lot of hoops to do what Visual Code can already handle natively. Having it run a VS Code server in your `php` container means that all of the extensions are run on the remote filesystem, rather than locally. This removes the need to run a custom command at all since the paths and everything will already be absolute using the remote filesystem.

I'm torn about whether or not an extension like this should support an obscure use case. I wouldn't be opposed to adding the feature, I'd just like to understand why it's needed in the first place.

**Comment by lumnn** [comment]
I'll try to keep it only about `executable` and related to command executing.

All of that is without "Auto executable" option enabled.

I've tried already few times commands like "php7 vendor/bin/phpcs" which didn't work and I'm not sure why, because extension output panel is empty - I'm not really sure how to check logs as VSCode is not my daily driver. You should be able to reproduce the issue by using `php vendor/bin/phpcs` as an executable.

The problem with executable is that it expects executable file, not the command, which is restricting a bit what can be put there. In other words based on what I saw in the code, executable value is directly passed as a first argument to `child_process.spawn` method

Consider this example with `ls` that's certainly on your computer.

```js
const { spawn } = require('node:child_process');

const ls = spawn('ls', ['-la']);
const lsla = spawn('ls -la');
```

It will break beacuse of the line 4 with `ls -la` being the command that's executed, not the executable. Same happens when I put `php7 vendor/bin/phpcs` which is not an executable but rather a command.

**What I'd suggest as a fix?**

Based on what extension for editors do as well as number of platforms that allow specifying commands, I believe the best would be to allow `executable` to be either a string or array. If it's string, nothing changes.
If it's array, then it's first element should be passed to the `spawn` as a first argument, and rest would be prepended to the `processArgument` array here https://github.com/ObliviousHarmony/vscode-php-codesniffer/blob/161844e5cf9b05699b9b6a51590de9a90da7a76e/src/phpcs-report/worker.ts#L169

**Comment by ObliviousHarmony** [comment]
I see @lumnn, that makes sense. Since `spawn` only ever takes an executable, I think I'd rather keep the setting as a string and just break on spaces to populate the front of the `processArguments` array. The only edge case to consider here would be spaces in Windows paths where we would allow for quoted strings to have spaces. Thanks for raising this issue!

**Comment by ObliviousHarmony** [comment]
I've released a new version fixing the executable problem @lumnn. It won't help with the Docker use-case, but, it will let you run different versions of PHP.
