### ISSUE TITLE
Allow folder settings for standard and standardCustom

### ISSUE THREAD

**Issue by dvdmlln** [ObliviousHarmony/vscode-php-codesniffer#88]
### Problem Description

The settings `standard` and `standardCustom` can not be overridden by folder settings but only by user, remote and workspace settings. However, it would be useful to override these settings for specific folders, for example if you have a workspace containing multiple folders where the location of the `standardCustom` file differs.

### Proposed Solution

Change scope of these settings. May be usefol for other settings (ignorePatterns) as well?

**Comment by ObliviousHarmony** [comment]
One caveat here is that Standard Custom and Ignore Patterns look at the path as relative to the workspace root. If we used a "resource" scope this might be confusing since the path would still be relative to the root of the workspace. It also feels like it would be confusing to have it change circumstantially though based on whether this was configured or not.

What do you think? It might make sense for the standard to be resource scoped but the custom path doesn't feel right to me.

**Comment by dvdmlln** [comment]
Thanks for your quick repsonse! I agree that it might be confusing, but consider you have a multi-root workspace and each root has its own phpcs.xml in a different location. There would be no way to set the custom path or do I miss something?

**Comment by ObliviousHarmony** [comment]
> consider you have a multi-root workspace and each root has its own phpcs.xml in a different location

Interesting, I was under the impression that the `"window"` scope would let you change settings for each workspace root rather than requiring you to set one for _all_ workspaces. [This does not seem to be the case](https://code.visualstudio.com/docs/getstarted/settings#_settings-precedence) and `"resource"` means the workspace folder. I'm thinking the following is appropriate:

- [ ] Change all `"window"` scopes to `"resource"`.
- [ ] Test the extension in a multi-root workspace and make sure automatic executable and standard detection work.
- [ ] Verify that the working directory is set correctly in a multi-root workspace.

**Comment by ObliviousHarmony** [comment]
Hey @dvdmlln,

I've release version 2.3.0 that includes these changes.

**Comment by dvdmlln** [comment]
Great, thank you!
