### ISSUE TITLE
Path to windows executable can't handle spaces

### ISSUE THREAD

**Issue by es-sayers** [ObliviousHarmony/vscode-php-codesniffer#97]
### Description

Unable to have a space in the file path to the windows PHPCS executable.

### Reproduction Steps

1. Go to Extension settings
2. Scroll down to PHP Code Sniffer > Exec: Windows
3. Enter C:\Users\User Name\path\to\executable or quoted "C:\Users\User Name\path\to\executable"
4. See error "The PHPCS executable "C:\Users\User" could not be found."

### Expected Behavior

Expected the executable to be found.

**Comment by ObliviousHarmony** [comment]
Thanks @es-sayers,

It looks like there's a problem with the handling of quoted strings when using Windows directory separators. If you use `/` instead for your path (`"C:/Users/User Name/path/to/executable"`) it should work. Note that you _do_ need to escape the path. This is because the executable option supports the use of spaces to create more complicated commands such as running it via `docker`.

Definitely still something to fix though.
